/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PessimisticRouteImport } from './routes/pessimistic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiTodosIdRouteImport } from './routes/api/todos.$id'

const PessimisticRoute = PessimisticRouteImport.update({
  id: '/pessimistic',
  path: '/pessimistic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosIdRoute = ApiTodosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTodosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pessimistic': typeof PessimisticRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/api/todos/$id': typeof ApiTodosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pessimistic': typeof PessimisticRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/api/todos/$id': typeof ApiTodosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pessimistic': typeof PessimisticRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/api/todos/$id': typeof ApiTodosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pessimistic'
    | '/api/categories'
    | '/api/todos'
    | '/api/users'
    | '/api/todos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pessimistic'
    | '/api/categories'
    | '/api/todos'
    | '/api/users'
    | '/api/todos/$id'
  id:
    | '__root__'
    | '/'
    | '/pessimistic'
    | '/api/categories'
    | '/api/todos'
    | '/api/users'
    | '/api/todos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PessimisticRoute: typeof PessimisticRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiTodosRoute: typeof ApiTodosRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pessimistic': {
      id: '/pessimistic'
      path: '/pessimistic'
      fullPath: '/pessimistic'
      preLoaderRoute: typeof PessimisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos/$id': {
      id: '/api/todos/$id'
      path: '/$id'
      fullPath: '/api/todos/$id'
      preLoaderRoute: typeof ApiTodosIdRouteImport
      parentRoute: typeof ApiTodosRoute
    }
  }
}

interface ApiTodosRouteChildren {
  ApiTodosIdRoute: typeof ApiTodosIdRoute
}

const ApiTodosRouteChildren: ApiTodosRouteChildren = {
  ApiTodosIdRoute: ApiTodosIdRoute,
}

const ApiTodosRouteWithChildren = ApiTodosRoute._addFileChildren(
  ApiTodosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PessimisticRoute: PessimisticRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiTodosRoute: ApiTodosRouteWithChildren,
  ApiUsersRoute: ApiUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
